### PR TITLE
This pull request add windows build through Travis-CI, plus upload of the build on Github Release.

### PR DESCRIPTION
**Pull request by mcarbonneaux**
This pull request add windows build through Travis-CI, plus upload of the build on Github Release.
Each time you add a release (tag), Travis-CI is launch and at this end of the build upload the builded exe to Github release.

You need to create Github Personal Token (with you own account or with Github Machine user) with scop repo for the upload.

Like her https://github.com/mcarbonneaux/proxytunnel/releases/tag/v1.10.20200716.

image

### CODE REVIEW

**Comment by mcarbonneaux** [comment]
Sorry you must change de build badge on Readme.md to reflect the build state of YOUR repository.

**Comment by mcarbonneaux** [comment]
To use this deploy script:
 - You must generate 'Personal access token' with repo scope of this repository.
 - You must add Variable GITHUB_UPLOAD_TOKEN in settings of your project in travis setting.
 - GITHUB_UPLOAD_TOKEN must contain the token.
 - You can create the token on 'machine user' in place of the 'owner user' of this repository for more security.

**Comment by mcarbonneaux** [comment]
the last while seem to be ok, but you need to create a tag (the push of the artifact are create on tag).

**Comment by mcarbonneaux** [comment]
ok is in good way https://github.com/proxytunnel/proxytunnel/releases/tag/v1.10.20200907 ... 

but you need to add variable GITHUB_UPLOAD_TOKEN (token that you must create in your user interface in [here](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with `repo scope`)  to travis ci to push to builded binary to tag release....

image

in travis interface you can see that you do not have setted variable:
image

you must set it in:

image

here :
image

**Comment by nikita1211** [comment]
Hi @sigio , @mcarbonneaux , the build through Travis-CI is pushing the source code but not the binary to GitHub release page. Please can we get the binary as well to the release page by adding the TOKEN variable required. It would be great to get the binary for Windows. Thank you

**Comment by mcarbonneaux** [comment]
@sigio  can you create token like i explaint [bellow](https://github.com/proxytunnel/proxytunnel/pull/47#issuecomment-693603579) to make travis ci to push windows binary to the github release ?!

**Comment by sigio** [comment]
Did that... but still doesn't seem to upload anything ?

Last lines of the travis buildlog:
gcc -o proxytunnel -Wall -O2 -ggdb -DOPENSSL11 -DHAVE_GETOPT_LONG -DUSE_SSL -DSETPROCTITLE -DSPT_TYPE=2 -DSO_REUSEPORT proxytunnel.o base64.o strzcat.o setproctitle.o io.o http.o basicauth.o globals.o readpassphrase.o messages.o cmdline.o ntlm.o ptstream.o strlcpy.o strlcat.o -lssl -lcrypto
Copy msys/openssl dll to build dir...
Generate proxytunnel.zip with docs, exe and msys/openssl dll...
  adding: proxytunnel.exe (deflated 65%)
  adding: msys-2.0.dll (deflated 63%)
  adding: msys-crypto-1.1.dll (deflated 53%)
  adding: msys-ssl-1.1.dll (deflated 59%)
  adding: msys-z.dll (deflated 47%)
  adding: docs/proxytunnel.1 (deflated 70%)
  adding: docs/proxytunnel.1.html (deflated 74%)
  adding: docs/proxytunnel-paper.html (deflated 72%)
Warn: AUTHOR sect.: no personblurb|contrib for Proxytunnel develo  proxytunnel
Note: AUTHOR sect.: see http://www.docbook.org/tdg5/en/html/contr  proxytunnel
Note: AUTHOR sect.: see http://www.docbook.org/tdg5/en/html/perso  proxytunnel
Note: Writing proxytunnel.1
io.c: In function ‘readline’:
io.c:61:3: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   61 |   strncpy( dstr, buf, strlen(buf));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by sigio** [comment]
Also... looks like travis-ci.org is shutting down this month...

**Comment by sigio** [comment]
GITHUB_UPLOAD_TOKEN are null, you must create Github Personal Access Token to use this script...
562

While it was set.... trying again...

**Comment by sigio** [comment]
Ok.... needs to be available on all branches it seems... build is done now ;)

https://github.com/proxytunnel/proxytunnel/releases/download/v1.10.20210604/proxytunnel.zip

**Comment by mcarbonneaux** [comment]
> 
> 
> Also... looks like travis-ci.org is shutting down this month...

travis-ci.com replace .org for free for opensource project you need to simply migrate to it (simply create an account on travis-ci.com and link it to your github account).

**Pull request merged**
